# Site settings
title: Gentoo Linux

# Build settings
markdown: kramdown

# No slash at the end
cdnurl: https://1b9a50f4f9de4348cd9f-e703bc50ba0aa66772a874f8c7698be7.ssl.cf5.rackcdn.com
contact: http://www.gentoo.org/main/en/contact.xml
copyrightyears: "2001&ndash;2014"